import {
  Baby,
  Bath,
  Bed,
  Building,
  Car,
  Check,
  CircleDollarSign,
  Coffee,
  Dumbbell,
  Eye,
  Flame,
  GlassWater,
  Home,
  Mountain,
  PartyPopper,
  PawPrint,
  Snowflake,
  Sofa,
  Sparkles,
  Sunrise,
  TreePine,
  Tv,
  UtensilsCrossed,
  Warehouse,
  Waves,
  Wifi,
} from "lucide-react";

export const iconMap = {
  "Ban công": Sunrise,
  "Bao gồm bữa sáng": UtensilsCrossed,
  "Bàn làm việc": Home,
  "Bãi biển": Waves,
  "Bãi đỗ xe": Car,
  Bếp: Home,
  "Bồn tắm nước nóng": Bath,
  "Bữa sáng miễn phí": UtensilsCrossed,
  "Dịch vụ lễ tân": Check,
  "Dịch vụ phòng": Bed,
  "Dịch vụ quản gia": Check,
  "Dịch vụ xe": Car,
  "Hồ bơi": Waves,
  "Hồ bơi trên mái": Waves,
  "Lò sưởi": Flame,
  "Lễ tân": Check,
  Minibar: Coffee,
  "Miễn phí": CircleDollarSign,
  "Máy lạnh": Snowflake,
  "Nhà hàng": UtensilsCrossed,
  "Nhìn ra biển": Eye,
  "Nhìn ra núi": Mountain,
  "Nhìn ra thành phố": Building,
  "Nhìn ra vườn": TreePine,
  "Phòng khách": Sofa,
  "Phòng tập": Dumbbell,
  "Quán bar": GlassWater,
  Spa: Sparkles,
  "Sân riêng": Warehouse,
  "Thú cưng": PawPrint,
  "Tiếp cận hồ bơi": Waves,
  "Tiếp cận Spa": Sparkles,
  Tiệc: PartyPopper,
  "Tour lịch sử": Building,
  "Trung tâm kinh doanh": Building,
  "Trượt tuyết": Mountain,
  "Trẻ em": Baby,
  "TV thông smart": Tv,
  "Tầm nhìn toàn cảnh": Eye,
  Vườn: TreePine,
  "WiFi cao cấp": Wifi,
  "WiFi miễn phí": Wifi,
  "Điều hòa": Snowflake,
};

export const getAmenityIcon = (amenityName) => {
  return iconMap[amenityName] || Check;
};
